M48
; DRILL file {KiCad (6.0.11)} date Mon Nov 25 11:33:14 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-25T11:33:14+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X66.0Y-61.0
X66.0Y-163.0
X358.0Y-61.0
X358.0Y-163.0
T0
M30
